### ISSUE TITLE
error on starting stepmania

### ISSUE THREAD

**Issue by fireandice1989** [GrooveStats/gslauncher#10]
![screen](https://user-images.githubusercontent.com/99900761/154529053-97b58988-fbb2-46ff-b126-59a0060afaed.jpg)

I'm getting this error when starting stepmania. It worked just fine before and I haven't done anything special

this is the crash log

```
2022/02/17 09:36:59 GrooveStats Launcher 1.2.0 (linux amd64)
2022/02/17 09:36:59 Fyne error:  Settings watch error:
2022/02/17 09:36:59   Cause: no space left on device
2022/02/17 09:36:59   At: /root/go/pkg/mod/fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:19
```

**Comment by Dominick-Peluso-Bose** [comment]
Can you make sure the directories gslauncher is configured for all have space left? And that they are writable? 

gslauncher does read and write files such as logs and unlocks which can grow over time. If you ran out of space, I imagine it would give you an error like this.

**Comment by fireandice1989** [comment]
yes, everything is in order-there's plenty of space on the drive. How else can I help with troubleshooting?

**Comment by fireandice1989** [comment]
looks like if  run this as root it works... how do I make sure the permissions are correct? I checked that all users have write access in the file explorer (I'm using lubuntu btw)
![screen](https://user-images.githubusercontent.com/99900761/154611281-f8bc2937-d5b5-4c6a-a7e4-91f7d8c40eb4.jpg)

**Comment by fireandice1989** [comment]
absolutely. here's that output
![screen](https://user-images.githubusercontent.com/99900761/154814087-5d2a25e4-182c-4ed2-b81a-6c7030d3a0fc.jpg)

**Comment by Roujo** [comment]
Ah darn, it looks like you have enough space on all of your filesystems, so your issue lies elsewhere. It was worth a shot. 😅

**Comment by natano** [comment]
@fireandice1989 I think your issue might be caused by the system running out of inotify watchers. See [this thread](https://askubuntu.com/a/1088275) for instructions how to increase the number of available inotify watchers.

**Comment by fireandice1989** [comment]
@natano increasing inotifiers worked! For anyone else, this is how I did it:

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

**Comment by natano** [comment]
Glad it worked!
