### ISSUE TITLE
version 1.3.1 needs MacOS 12

### ISSUE THREAD

**Issue by snil4** [GrooveStats/gslauncher#12]
Just installed 1.3.1 on my MacBook Air M1 and I get this error: "You have macOS 11.6.2. The application requires macOS 12.0 or later." Any quick way to fix it without updating?

**Comment by natano** [comment]
Hey, the version that is required for running the app is based on which version of macOS I use to build it.

I think I *might* have found a way to build for older macOS versions, but I can't try it out myself. Can you give [this beta build](https://www.natano.net/static/data/tmp/gslauncher-macos10.12-beta1/) a shot, @snil4?

**Comment by snil4** [comment]
This build works, it boots stepmania, connects to groovestats no problem and it seems to get leaderboards just fine but I didn't have much time to test it more in depth. Thanks for the huge effort and this amazing software.

**Comment by natano** [comment]
I updated the dmg images for macOS in the v1.3.1release.
Thanks for the report, and have fun!
