### ISSUE TITLE
Songs and Save folders required to be in same directory

### ISSUE THREAD

**Issue by seaschell1** [GrooveStats/gslauncher#3]
- In order to run gslauncher, the "Songs" and "Save" folders must exist in the same directory. For Linux and Mac users, the Save data defaults to saving in a separate hidden directory (".stepmania" instead of "stepmania")

**Comment by seaschell1** [comment]
Current workaround is to create a symbolic link (to the Save folder) in the directory containing the Songs folder.

i.e. 
Navigate the Songs folder and run:
ln -s <path to Save folder> ./Save

**Comment by natano** [comment]
In the next release it will be possible to ocnfigure Save/ and Songs/ separately.
