### ISSUE TITLE
Linux script fails if /opt directory doesn't exist

### ISSUE THREAD

**Issue by teejusb** [GrooveStats/gslauncher#4]
`/opt` isn't a directory available on all Linux distros so it the script fails when trying to create the gslauncher file in that folder.

A fix is to run ` sudo mkdir /opt` at the start if it doesn't exist.

![image](https://user-images.githubusercontent.com/5017202/117725900-a66a5b00-b19a-11eb-99b5-f5ed5348d9bc.png)

**Comment by natano** [comment]
I fixed the linux setup script for the next release.
