### ISSUE TITLE
Launching StepMania from the GsLauncher locks up sound

### ISSUE THREAD

**Issue by teejusb** [GrooveStats/gslauncher#6]
This one is a bit more nuanced and I'm not quite sure what's happening.

I'm on Xubuntu 64-bit

If I start the launcher and attempt to launch StepMania by clicking the button, StepMania will start but no sound will be played. In StepMania's `log.txt` I see

`00:00.113: Couldn't load driver ALSA-sw: dsnd_pcm_open(dmix:0,0): Device or resource busy`

Which implies to me that launching StepMania through the launcher takes control of Alsa which then causes StepMania to fail trying to access the sound driver.

Interestingly, I don't have this issue when I have the launcher open and I open StepMania separately outside of it. This leads me to believe that something is happening specifically when launching StepMania through the launcher. In this case I do get sound but the game doesn't acknowledge the already-open launcher so I don't get any online functionality,

**Comment by natano** [comment]
Did you try setting your `SoundDevice` to something else? At home I use `SoundDevice=hw:0` with the launcher and it works. I don't do anything audio related in the launcher, but maybe some environment variables have to be passed along for certain sound setups when launching SM?

**Comment by natano** [comment]
Is there anything relating alsa or pulseaudio in your environment variables? (look at the output of `env`)

**Comment by teejusb** [comment]
Doesn't seem to be. I eyeballed the output of `env` and also grepped for `alsa`, `pulse`, `sound`, and `audio` and there were no results.

**Comment by natano** [comment]
It was some issue unrelated to the launcher.
