### ISSUE TITLE
Wrong executable path on OutFox Alpha 4.11+

### ISSUE THREAD

**Issue by lucdar** [GrooveStats/gslauncher#9]
I receive the following error when trying to launch StepMania through the launcher using OutFox Alpha 4.11: 

`failed to run StepMania: fork/exec /Applications/OutFox/OutFox.app/Contents/MacOS/StepMania: no such file or directory`

I think this is because in OutFox alpha 4.11 the executable in the MacOS OutFox.app was renamed to `OutFox` from `StepMania`.

**Comment by natano** [comment]
Thanks for the report, @lucdar! I will include a fix for it in the next release. Please use the latest alpha where the binary is called `StepMania` in the meantime.
